services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projectx'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
