version: '3.8'

services:
  app:
    image: raaphiixx/projectx:2.2
    container_name: projectx
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectx
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      DATABASE_HOSTNAME: db
      REDIS_HOSTNAME: redis
    ports:
      - "8080:8080"
    networks:
      - projectxNet

  db:
    image: raaphiixx/projectx-db:1.0
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projectx
    ports:
      - "5432:5432"
    networks:
      - projectxNet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - projectxNet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local

networks:
  projectxNet:
    driver: bridge
